Restructure instruction fusion code
aayasin/perf-tools pull request #36
Opened 2023-10-05 22:25 UTC by amiri-khalil

2023-10-08 12:47 UTC, aayasin requested changes
Amiri, enclosed more review comments to be addressed.

2023-10-08 12:47 UTC, aayasin commented on lbr.py
> +Insts_MF2 = [x + '-OP fusible' for x in ['MOV', 'LD']]
rename Insts_MF2 to Insts_Fusions e.g.

2023-10-08 12:47 UTC, aayasin commented on lbr.py
> +  def edge_stats():
Thanks for adding this function.
Please hoist it outside read_sample() and pass what's needed, like lines, to it.

2023-10-08 12:47 UTC, aayasin commented on lbr.py
> +  if log: C.fappend(res, log)
how about 1 line:

C.fappend(res, log) if log else print(res)

2023-10-08 12:47 UTC, aayasin commented on stats.py
> +def print_candidate_stats(hitcounts, info):
I would rename it to inst_fusions()
I wouldn't stress 'print' and stats is module's name.

2023-10-08 12:47 UTC, aayasin commented on stats.py
> +    print_stat('%s fusible-candidate' % stat, value, ratio_of=('ALL', total), log=info)
Great code reuse :)

2023-10-08 12:47 UTC, aayasin commented on stats.py
> +    condition = lambda l: 'mov' in l and not x86.is_mem_store(l)
renaming condition to is_MOV make helps readability.

2023-10-08 12:47 UTC, aayasin commented on stats.py
> +            hotness_key, block = hotness(line), [line]  # restart for next block
how about making this a tiny restart() local function that is invoked here, and in lines 354-355, and also for next line when overriding default args, for example.

2023-10-08 13:40 UTC, amiri-khalil commented on kernels/x86.py
> +          ['r' + str(n) + 'd' for n in range(8, 16)]
Yes, notice the 'd' there, e.g. r8d is the 32-bit reg for r8, and so on.

2023-10-09 09:57 UTC, aayasin approved these changes
Thanks for addressing online review comments

2023-10-09 09:58 UTC, merged